### PR TITLE
Final Proposal

### PR DESCRIPTION
**Pull request by JoeChildress**
Sorry this is a little late. Pet related emergency. Please review. Thanks

### CODE REVIEW

**Comment by JoeChildress** [comment]
Please review my final project files. 

Wasn't too sure about dealing with a form view and handling the submit event. But, this version should fulfill the requirements. Please let me know if not. 

Thanks

**Comment by jamdon** [comment]
When I run your app, I can see the todos as I add them, but if I refresh the page, they're not there. Your POST is returning 500 errors, and I believe it's related to the fact that you're not actually connecting to your database. Check the name of your db and make sure you're connecting to the right db name.

**Comment by JoeChildress** [comment]
Ah okay. I'll look into it. Thanks.

**Comment by JoeChildress** [comment]
Away from my computer for a bit. If I'm using a mongo db, do I need to provide more than the models to load into the db and set the router for the api? Thanks.

**Comment by JoeChildress** [comment]
Okay, the name of the db. Just reread that while not walking. Okay. I'll
update that. Thanks!

**Comment by JoeChildress** [comment]
Uploaded a new todoJSON.js file and changed the db name to todoAPI which matches with the mongoose url in index.js. Hope that is the fix for the issue. Thanks.

**Comment by JoeChildress** [comment]
Made some minor updates to the files. Nothing major with the js except escaping in the template. I think it 's ready for grading. Feel free to unless you something glaring. I'm assuming I have fulfilled the project requirements. I will definitely be making improvements to the code later.  Thanks.

**Comment by jamdon** [comment]
Looks good. Congrats on building your full-stack app! 👍

**Pull request closed without merging**
