### PR TITLE
updated with project proposal

### PR DESCRIPTION
**Pull request by fushen16**
Project Proposal

### CODE REVIEW

**Comment by jamdon** [comment]
This is looking good! My question is are you implementing another route? Right now your Backbone router doesn't really do anything. Also, all your Backbone components should be modules. They don't have to be CommonJS format, but they do need to be modules. It would be as simple as:

`App.Views.App = (function () {  
   return Backbone.View.extend({  
     /* your view implementation here */
 })();`

**Comment by fushen16** [comment]
I agree with your assessment.

I will try to modify the code and see how much change I can do in a day. :-)

Fulin

On Fri, Jun 17, 2016 at 5:00 PM, jamdon notifications@github.com wrote:

> This is looking good! My question is are you implementing another route?
> Right now your Backbone router doesn't really do anything. Also, all your
> Backbone components should be modules. They don't have to be CommonJS
> format, but they do need to be modules. It would be as simple as:
> 
> App.Views.App = (function () {
> return Backbone.View.extend({
> /\* your view implementation here */
> });
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/JSCRIPT300-Spring2016/Final_Project/pull/8#issuecomment-226907688,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARdszH4UxLlT-wD2OgwfIJwos9cquiBqks5qMzUmgaJpZM4ITPf_
> .

## 

Fulin Shen
541-357-8618

**Comment by jamdon** [comment]
Hi Fulin,

Just checking in to see if you were still working on this, and wanted me to wait, or if you're ready to have it graded.

**Comment by fushen16** [comment]
Hi, James:

Looks like I don't have enough time to get another client route working. You can grade it as is. Thanks.

Fulin

**Comment by jamdon** [comment]
👍

**Pull request closed without merging**
