### PR TITLE
final project

### PR DESCRIPTION
**Pull request by imastudent99**
my todo app final project. I also deployed the app on AWS @ http://todo-env.us-west-2.elasticbeanstalk.com.

### CODE REVIEW

**Comment by jamdon** [comment]
Is this just an initial commit? I ask because I'm not finding anything that meets requirement #4 for the final project (i.e. a Backbone application.)

**Comment by imastudent99** [comment]
This is it as I don't see getting the backbone part complete by Sat.

**Comment by jamdon** [comment]
Ok, I'll grade it as is come Saturday.

**Comment by jamdon** [comment]
👍

**Pull request closed without merging**
