### PR TITLE
final project proposal

### PR DESCRIPTION
**Pull request by BenBagBag**

### CODE REVIEW

**Comment by BenBagBag** [comment]
@jamdon This is my first stab at getting this working. Where I'm getting really confused (because we worked with Backbone directly in the browser in class) is:
-how do I connect the routes in `index.js` to the Backbone collection and then to the views (in other words, how do I use those routes to get info from/put info into the collection, and then put that info into the views? I currently have dummy values in `listofplants.js` just to test it)? 
-why is my .less file not coming through? I tried putting in some random CSS just to make sure it worked and it doesn't change the style, and when you look at it in the sources tab in Chrome, the file appears to be blank. (This isn't as important). 

Help is much appreciated!

**Comment by jamdon** [comment]
Hi Isaac,

You connect your Backbone Collection up to a RESTful endpoint by specifying
a url property when extending Backbone Collection (and by specifying a
urlRoot when extending a Backbone Model.) Backbone figures out what to do
with that once you try to do something like fetch or save. One thing you
still need to do, if you're attaching to existing DOM elements, is wrap
your app's code in a jQuery ready block. You're referencing DOM elements to
attach your views to, but you have to make sure the DOM has been
constructed and is ready before you do so. I recommend having a separate
client.js or main.js file where you do this. As for your .less files, I
don't use less, but I have to wonder if you shouldn't be compiling your
less files to .css files first before trying to use them in the browser?

thanks,

James

**Comment by BenBagBag** [comment]
@jamdon 
Hi James,

I tried adding in a main.js file with an initialize function, but no dice (I also tried reworking the collection some so I could wire that up directly to render the list of plants (plant.js and listofplants.js). I'm not sure where I'm going wrong with this?

I'll look into .less compiling, and if all else fails, I'll just go back to .css.

**Comment by jamdon** [comment]
Hi Isaac,

I'm still not seeing a jQuery ready block in your code. You're not going to be able to attach to DOM elements with views if you're trying to do it without waiting for the DOM to be ready.

thanks,

James

**Comment by BenBagBag** [comment]
@jamdon Hi James,
I guess my disconnect is in two places:
a) I fiddled some more, and after fixing a script tag, I was able to render the header.js view in index.html without ever using a jQuery ready block, so it seems that you don't necessarily need one. (For an example of a Backbone project without a ready block, see here: https://github.com/ccoenraets/nodecellar)
b) I'm not totally sure where you'd put the ready block--wrap everything in the main.js file in a ready block?

I got the Header view working, and I got the ListOfPlants view rendered, except for the fact that it won't render a dynamic plant list using the collection PlantList. (I put a dummy html line in there to verify that the view is rendering, so I know that the problem is with the dynamic bit).

**Comment by jamdon** [comment]
Hi Isaac,

You're able to add HTML to jQuery selected elements most likely because your script is now running after the DOM is ready (by appearing at the bottom of your body element.) However, using a jQuery ready block allows two things: 1. you're guaranteed not to execute any of your code until the DOM is ready, regardless of where your script tag appears and 2. your code can be initialized without polluting the global scope since it's now running from inside a jQuery ready block (which just means it's inside of a function that's passed to jQuery). I haven't covered how to put all these components together that we've been learning about yet (next lecture) but I typically instantiate a top level component (can be a view or a router) that itself will instantiate the other elements I need. When I instantiate views that are attaching to existing DOM elements, I pass the el selector in as part of the initialization data for the view instance. This means that when my view code is instantiated, I want it guaranteed that the DOM is ready. This is as simple as instantiating your application inside a jQuery DOM ready block:

`$(function() {`
   // instantiate your application here
 `});`

inside your main.js.

Hope that clarifies what I meant.

thanks,

James

**Comment by BenBagBag** [comment]
@jamdon 
Hi James,

I'm having trouble with templates; I keep getting the error, "TFT is not defined" when trying to load the header template. Running grunt seems to go fine, and if I sub out the template reference in header.js, it works (see commented out code), so Backbone's components are coordinating fine. "TFT" is defined in the gruntfile, so what's wrong? I don't get it.

Thanks,

Isaac

**Comment by jamdon** [comment]
Hi Isaac,

Do you have the latest version of your code updated in your repository? If
so, send me a link to it and I can take a look at it to see what might be
happening.

thanks,

James

**Comment by jamdon** [comment]
It looks like you're never including templates.js as a script in your index.html. This is the file that will create the TFT namespace, so when one of your views references TFT.sometemplate, it won't find it, because templates.js was never loaded.

**Comment by BenBagBag** [comment]
That fixed it, thanks for the explanation.

On Sun, Jun 12, 2016 at 9:51 PM, jamdon notifications@github.com wrote:

> It looks like you're never including templates.js as a script in your
> index.html. This is the file that will create the TFT namespace, so when
> one of your views references TFT.sometemplate, it won't find it, because
> templates.js was never loaded.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/JSCRIPT300-Spring2016/Final_Project/pull/3#issuecomment-225474523,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHXFbnkD6Rv1Tsyfq7GUUykc-bQJHf_0ks5qLLeSgaJpZM4ISY61
> .

## 

Thanks,

Isaac

**Comment by jamdon** [comment]
Just checking in. If you want more feedback, be sure to update your p.r. fixing the templates reference issue and I'll pull down your latest and look at it again.

**Comment by BenBagBag** [comment]
@jamdon The templates are working (I'm going to go back and generate the lists from templates as a clean-up step, but I have two templates working so I think I'm good). Where I'm stuck now is on routing. I have the routes '/' and '/#planting' (I can't get non-hash routes to work, even with pushState:false). In https://github.com/BenBagBag/Final_Project/blob/master/routes/gardenRoutes.js I should have it set up so that a list of plants is returned (all plants, just to test the route itself, the function is here: https://github.com/BenBagBag/Final_Project/blob/master/garden.js). But when I go to http://localhost:3000/#planting, when it should log the list of plants (from https://github.com/BenBagBag/Final_Project/blob/master/public/controllers/mainController.js), nothing happens. The route does not trigger the get method, but I'm not sure why. It works for '/'. Any ideas?

(Edited to add: for some reason Github is being weird and taking away the diffs, so here's a link to my repo: https://github.com/BenBagBag/Final_Project)

**Comment by jamdon** [comment]
Hi Isaac,

I'll take a look at it tonight to see what I can see.

thanks,

James

**Comment by jamdon** [comment]
Hi Isaac,

Can you submit a p.r. for your project? Doing that allows me to comment on
code inline. Before you do, however, you need to remove your node modules
from your repo. I won't be able to comment on files if those are in your
repo because the file limit for displaying files will be exceeded. To do
so, delete your node_modules folder locally, git add, git commit, and git
push that change to your repo. Use a .gitignore file as discussed in class
to prevent your node_modules from being tracked by git.

thanks,

James

**Comment by BenBagBag** [comment]
Hi James,

Yes, here's the PR:
https://github.com/JSCRIPT300-Spring2016/Final_Project/pull/19

Thanks,

Isaac

On Sat, Jun 18, 2016 at 1:06 AM, jamdon notifications@github.com wrote:

> Hi Isaac,
> 
> Can you submit a p.r. for your project? Doing that allows me to comment on
> code inline. Before you do, however, you need to remove your node modules
> from your repo. I won't be able to comment on files if those are in your
> repo because the file limit for displaying files will be exceeded. To do
> so, delete your node_modules folder locally, git add, git commit, and git
> push that change to your repo. Use a .gitignore file as discussed in class
> to prevent your node_modules from being tracked by git.
> 
> thanks,
> 
> James
> 
> On Fri, Jun 17, 2016 at 6:15 PM, James Donaldson <kinakuta.james@gmail.com
> 
> > wrote:
> > 
> > Hi Isaac,
> > 
> > I'll take a look at it tonight to see what I can see.
> > 
> > thanks,
> > 
> > James
> > 
> > On Thu, Jun 16, 2016 at 11:49 PM, Isaac notifications@github.com
> > wrote:
> > 
> > > @jamdon https://github.com/jamdon The templates are working (I'm
> > > going
> > > to go back and generate the lists from templates as a clean-up step,
> > > but I
> > > have two templates working so I think I'm good). Where I'm stuck now is
> > > on
> > > routing. I have the routes '/' and '/#planting' (I can't get non-hash
> > > routes to work, even with pushState:false). In
> > > 
> > > https://github.com/BenBagBag/Final_Project/blob/master/routes/gardenRoutes.js
> > > I should have it set up so that a list of plants is returned (all
> > > plants,
> > > just to test the route itself, the function is here:
> > > https://github.com/BenBagBag/Final_Project/blob/master/garden.js). But
> > > when I go to http://localhost:3000/#planting, when it should log the
> > > list of plants (from
> > > 
> > > https://github.com/BenBagBag/Final_Project/blob/master/public/controllers/mainController.js
> > > ),
> > > nothing happens. The route does not trigger the get method, but I'm not
> > > sure why. It works for '/'. Any ideas?
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > > https://github.com/JSCRIPT300-Spring2016/Final_Project/pull/3#issuecomment-226693879
> > > ,
> > > or mute the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AKP81F_KucVC_bZ_HhngvbtYtCAegyetks5qMkNpgaJpZM4ISY61
> > > 
> > > .
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/JSCRIPT300-Spring2016/Final_Project/pull/3#issuecomment-226928581,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHXFbnqavVH9pwFGVG6BVKRk2oaJozdcks5qM6cQgaJpZM4ISY61
> .

## 

Thanks,

Isaac

**Pull request closed without merging**
